#!/bin/bash

# Usage:
#  importdb [site]

# Exit on errors
set -e

# Set variables.
git_dir=`git rev-parse --show-toplevel`
git_branch=`git rev-parse --abbrev-ref HEAD`
project=$1
drush_args="-y -r ${git_dir}/build/docroot -l ${project}.local"
echo "Drush args are ${drush_args}"

# Check if project exists.
if mysql "${project}" >/dev/null 2>&1 </dev/null
then
  echo "${project} found"
else
  echo "${project} does not exist (or I do not have permission to access it)"
  exit
fi

# Import DB.
echo "Emptying DB..."
mysql -e "DROP DATABASE ${project};"
mysql -e "CREATE DATABASE ${project};"
if [ -f "${HOME}/Desktop/${project}-${git_branch}-inter.sql" ]; then
  echo "Importing intermediate DB..."
  mysql ${project} < ~/Desktop/${project}-${git_branch}-inter.sql
else
  echo "Importing base DB..."
  mysql ${project} < ~/Desktop/*-${project}-*.sql
fi
mysql -e "SELECT concat('TRUNCATE TABLE ', TABLE_NAME, ';') FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '${project}' AND TABLE_NAME LIKE 'cache%'" | sed 1d | mysql ${project}

# Update DB.
echo "Updating DB..."
echo "(updates started at `date`)"
drush updb ${drush_args}
echo "Reverting features..."
drush fra ${drush_args}

# Post-setup activities.
if [ ! -f "${HOME}/Desktop/${project}-${git_branch}-inter.sql" ]; then
  echo "Enabling devel modules..."
  drush en stage_file_proxy dblog diff devel feeds_ui ${drush_args}
  echo "Running cron..."
  drush cron ${drush_args}
  echo "Dumping intermediate DB..."
  mysqldump ${project} > ~/Desktop/${project}-${git_branch}-inter.sql
fi
drush uli --uid=1 ${drush_args}
